#Common
server:
  port: 9096

#Hibernate config
hibernate:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  username: ${DB_USERNAME:user}
  password: ${DB_PASSWORD:pwd}
  database: ${DB_NAME:postgres}
  entities: com.mokhovav.goodcare_moex_info.entites

#RabbitMQ
spring:
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_API_PORT:5672}
    username: ${RMQ_USERNAME:user}
    password: ${RMQ_PASSWORD:pwd}


#slf4j Logger
logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%cyan(%d{ISO8601}) %highlight(%-5level) [%green(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] %m%n"
  level:
    root: info
    com.mokhovav: debug
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: logs/archived/application-debug.%d{yyyy-MM-dd}.%i.log