#Common
server:
  port: 9090

#Hibernate config
hibernate:
  prefix: jdbc:postgresql
  sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  driver-class-name: org.postgresql.Driver
  ddl-auto: update

  host: localhost
  port: 5432
  database: goodcare
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  entities:
    moex: com.mokhovav.goodcare_moex_info.entites

#slf4j Logger
logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] %m%n"
  level:
    root: info
    com.mokhovav: debug
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: logs/archived/application-debug.%d{yyyy-MM-dd}.%i.log